### ISSUE TITLE
Companion N466-467 radio.bin issue with X7

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5558]
You maybe aware of that but reading model and settings from radio (X7) from Companion N466/N467 result in an error.

![image](https://user-images.githubusercontent.com/985702/34319080-b347674e-e7d8-11e7-82da-2b47ed6f1496.png)

**Comment by 3djc** [comment]
indeed

**Comment by r41065** [comment]
Same Problem with Taranis X9d and Companion 222N473.....478, not testet with Versions below.
( Win7)
Ralf

**Comment by jtaylor2** [comment]
I am having the same problem with x9d on today's self build 2.2 with VS2015 and QT 5.7.
The opentxinterface line 185 call to OpenTxEepromInterface::load seems to be returning the wrong size from the call to boards.cpp line 84 getEEpromSize where it is returning EESIZE_9XRPRO (524288) instead of  EESIZE_TARANIS (32768).

I have fixed my local build by adding a return EESIZE_TARANIS; after line 103.
```
diff --git a/companion/src/firmwares/boards.cpp b/companion/src/firmwares/boards.cpp
index cc5323ae5..31972658d 100644
--- a/companion/src/firmwares/boards.cpp
+++ b/companion/src/firmwares/boards.cpp
@@ -101,6 +101,7 @@ const int Boards::getEEpromSize(Board::Type board)
     case BOARD_TARANIS_X9D:
     case BOARD_TARANIS_X9DP:
     case BOARD_TARANIS_X9E:
+         return EESIZE_TARANIS;
     case BOARD_UNKNOWN:
       return EESIZE_MAX;
     default:
```
I haven't been able to figure out what broke this so I'm reluctant to submit a PR with this change, but I can if it is appropriate.

**Comment by 3djc** [comment]
this is my breaking, the fix misses also an issue somewhere else, making a more thourough one

**Comment by capitaineflam25** [comment]
I'm still facing the issue with Companion N482 (2017-01-07), should i upgrade the radio firmware too (Actual eeprom version is 218 on my X7)

![image](https://user-images.githubusercontent.com/985702/34651120-2b37b57a-f3cc-11e7-95a3-d86e54b7e8ae.png)

**Comment by capitaineflam25** [comment]
Can you reopen the issue or should i create a new one ?

**Comment by bsongis** [comment]
@3djc do you know which commit broke this?

**Comment by 3djc** [comment]
yes and no. It was the PCBFLAMENCO that caused it, I failed. So I fix the failuere, but it seems to have creeped back, but a number of changes to those two files (boards..h board.cpp) have happened as well

**Comment by bsongis** [comment]
ok I will have a look, but during this week-end, I won't have enough time tonight

**Comment by capitaineflam25** [comment]
Thanks a lot, this time it's OK (Tested on latest NB : N494)

**Comment by 3djc** [comment]
Yeah, we had two different, completely unrelated issue creating the same sympthom, that did make the process more complexx, sorry
