### ISSUE TITLE
Trim travel wrong direction

### ISSUE THREAD

**Issue by doloebig** [opentx/opentx#8950]
if you set "weight" in Input Tab to negativ value trim travel always positiv

Opentx 2.3.14
TX Taranis X9D plus 2019

**Comment by 3djc** [comment]
By design

**Comment by hrenz** [comment]
No this is not a design flaw
This is a known bug of openTx
and has been known for many years.

It can be fixed very easily
If the Input stick is inverted, the corresponding trimmer must also be inverted.

Where was the exact same error
now fixed at ETHOS in the same way

**Comment by doloebig** [comment]
i will setup this way 
thx

**Comment by mpjf01** [comment]
Seems that hrenz is writing that the same "bug" exists in ETHOS. That's interesting given that we have been told from day 1 that ETHOS is not based on OpenTx and that it's all greenfields design and code (despite the obvious similarities). This is not the first such "bug" that has found its way from OpenTx to ETHOS, the RTC issue is one other.

**Comment by Eldenroot** [comment]
EdgeTx should be fine and working, try :)

**Comment by hrenz** [comment]
Yes, 
ETHOS had exactly the same error

Together with Bertrand we have fixed it.

If a stick is inverted in the inputs, 
the corresponding trimmer is also inverted.
This solved the problem.

**Comment by bsongis** [comment]
@mpjf01 As you are thinking that Ethos is based on OpenTX source code, here is the patch that you will need to fix this issue ;)

![image](https://user-images.githubusercontent.com/5603504/190091479-75f22f31-af1e-4930-9313-0978fbe9e0d6.png)

![image](https://user-images.githubusercontent.com/5603504/190092525-3d5ca030-5c61-44f6-b713-108471577b5e.png)

@hrenz I think it is not fixed yet in Ethos, the PR is open and I have still to push the button, I will do for next release

**Comment by doloebig** [comment]
can anyone tell where the code ne put in? i compile my one bin file
I was found many entries on the internet where people report this "bug" but no fix or change for it.
Also i dont know how to change trim setting to negativ.
BTW same Bug in Edge

Reg and THX 
Doro
